export const MUSCLE_GROUPS = [
  'Quadriceps',
  'Hamstrings',
  'Calves',
  'Hip Adductors',
  'Hip Abductors',
  'Hip Flexors',
  'Glutes',
  'Front Delts',
  'Rear Delts',
  'Side Delts',
  'Chest',
  'Lats',
  'Upper Back',
  'Lower Back',
  'Traps',
  'Biceps',
  'Triceps',
  'Forearms',
  'Upper Abs',
  'Lower Abs',
  'Obliques',
]
